In [2]:
import numpy as np

print("numpy practice")

**rows are days and columns are products**


In [4]:
data = np.array([
    [120, 150, 130],
    [100, 160, 120],
    [140, 170, 150],
    [130, 180, 160],
    [110, 140, 135],
    [150, 190, 175],
    [160, 200, 180]
])

In [5]:
data

array([[120, 150, 130],
       [100, 160, 120],
       [140, 170, 150],
       [130, 180, 160],
       [110, 140, 135],
       [150, 190, 175],
       [160, 200, 180]])

In [6]:
print("Raw Data")
print(data)


Raw Data
[[120 150 130]
 [100 160 120]
 [140 170 150]
 [130 180 160]
 [110 140 135]
 [150 190 175]
 [160 200 180]]


In [8]:
total_sales=np.sum(data)

In [9]:
avg = np.mean(data)

In [10]:
max= np.max(data)

In [12]:
min= np.min(data)

In [13]:
print("Sales", total_sales)
print("avg", avg)
print("max",max)
print("min",min)

Sales 3150
avg 150.0
max 200
min 100


** axis = 0 (column-wise) to find which product perform best and axis= 1 (row wise) to find which day has high earnings**

In [14]:
product_totals = np.sum(data, axis=0)
product_avg = np.mean(data, axis=0)


In [15]:
daily_totals = np.sum(data, axis=1)

In [16]:
for i , total in enumerate(daily_totals):
    print(f"Day{i+1}:Total_sales={total}")

Day1:Total_sales=400
Day2:Total_sales=380
Day3:Total_sales=460
Day4:Total_sales=470
Day5:Total_sales=385
Day6:Total_sales=515
Day7:Total_sales=540


In [18]:
print()

In [21]:
normalized = (data - np.min(data)) / (np.max(data) - np.min(data))

In [23]:
print("Normalized Data:")
print(normalized)
print()

Normalized Data:
[[0.2  0.5  0.3 ]
 [0.   0.6  0.2 ]
 [0.4  0.7  0.5 ]
 [0.3  0.8  0.6 ]
 [0.1  0.4  0.35]
 [0.5  0.9  0.75]
 [0.6  1.   0.8 ]]



In [25]:
best_day = np.argmax(daily_totals) + 1
best_product = np.argmax(product_totals) + 1

In [26]:
print(f"Best Sales Day: Day {best_day}")
print(f"Best Product: Product {best_product}")

print("End")

Best Sales Day: Day 7
Best Product: Product 2
End
